In [5]:
import numpy as np

In [3]:
class SVM:
    def __init__(self, max_iter=100, kernel='linear'):
        self.max_iter = max_iter
        self._kernel = kernel
    
    def init_args(self, features, labels):
        self.m, self.n = features.shape
        self.X = features
        self.Y = labels
        self.b = 0.0
        
        self.alpha = np.zeros(self.m)
        # 将 Ei 保存在一个 (m,) 的 array 中
        self.E = self._E()
        self.C = 1.0
    
    # 返回 (m,) 的 array，保存每个训练样本预测值与真实值之差
    def _E(self):
        
        # 返回 (m,) 的 array，保存每个训练样本的预测值
        g = (self.alpha * self.Y) @ self.Kernel(X) + self.b 
        
        return g - self.Y

In [41]:
a = np.zeros(3)
a.shape

(3,)

In [42]:
Y = np.ones(3)
Y

array([1., 1., 1.])

In [43]:
(a * Y).shape

(3,)

In [44]:
X = np.array([[1,1],[3,4],[5,6]])
X.shape

(3, 2)

In [45]:
X[1]

array([3, 4])

In [46]:
X[1,:].shape

(2,)

In [47]:
X @ X.T

array([[ 2,  7, 11],
       [ 7, 25, 39],
       [11, 39, 61]])

In [48]:
((a * Y).T @ (X @ X.T)).shape

(3,)

In [49]:
c = ((a * Y).T @ (X @ X.T))

In [50]:
c.shape

(3,)

In [53]:
(c - Y).shape

(3,)